### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by Nidhibarthwal** [django-admin-bootstrap/django-admin-bootstrap#100]
Design in disturbed slightly due to base.css in admin folder. But I am not able to find that location

**Comment by douglasmiranda** [comment]
Django has it's own base.css, locate at: https://github.com/django/django/tree/master/django/contrib/admin/static/admin/css

I'm overriding the Django Admin's base.css, so we have one at:
https://github.com/django-admin-bootstrap/django-admin-bootstrap/blob/master/bootstrap_admin/static/admin/css/base.css

You will find both of them in your virtualenv folder, if you are using virtualenv.

If your problem it's with overriding templates / static files of existing packages, you may find useful:
https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#admin-overriding-templates

Don't know if I did answer your question, so let me know. =]

**Comment by douglasmiranda** [comment]
Closing for now, reopen if this persists.
