### ISSUE TITLE
Can you provide the source code under dashboard.js more pretty

### ISSUE THREAD

**Issue by malongge** [django-admin-bootstrap/django-admin-bootstrap#102]
i wan't to contribute dashboard.js, but the source code not pretty to understand, so could you help give the more pretty code, 3q!

**Comment by douglasmiranda** [comment]
Hey @malongge thanks for your interest xD

That minified code, it's just the code from: http://listjs.com

Have you found a bug on the listjs?

From the line 3 and below It's not minified. https://github.com/django-admin-bootstrap/django-admin-bootstrap/blob/master/bootstrap_admin/static/bootstrap_admin/js/dashboard.js
