### ISSUE TITLE
admin page layout confusion..

### ISSUE THREAD

**Issue by Ehco1996** [django-admin-bootstrap/django-admin-bootstrap#104]
![2017-04-19 10 44 24](https://cloud.githubusercontent.com/assets/24697284/25186234/2ccabbce-2552-11e7-95f5-d680848ef3b7.png)
like this . 
i think is the css file somehow blow out...
please help me
thanks !

**Comment by DovRine** [comment]
This seems to have corrected itself automatically for me, but I'm not sure why. It may be as simple as waiting for the static files to have been collected, but, just in case, I did the following:

Restart the dev server after installing this package.
Refresh the site without cache.
Open Chrome Dev Tools.
Manually change the viewport size past a bootstrap3 break point.

This was when everything started laying out correctly for me.

**Comment by KrazyMax** [comment]
I've got the exact same issue, but I noticed it works perfectly fine on my `localhost:8000/admin`, but not on my local wifi network (`192.XXX.XXX.XXX/admin`). I tried to investigate but for now I can not find why it is not working.

**Comment by douglasmiranda** [comment]
Prod servers:
- cache 
- collect static
- check your static url

Dev:
- most of the time it's cache

If it doesn't fit, you have to provide a demo or steps to reproduce the issue, closing for now, if it persists, we can reopen if you provide the steps or more details.

**Comment by KrazyMax** [comment]
Sorry I should have been more explicit. I meet the issue only on dev server (never tried prod yet). But:
* `python manage.py runserver` -> works just fine
* `python manage.py runserver 192.168.1.81:8080` -> will make incoherent HMI.

Not sure if this helps, but that's just what's going wrong with me! Notice that I do not change anything in my `settings.py` or anything else actually.

If I find an answer to why it does not work for me I will come back!

**Comment by douglasmiranda** [comment]
Here it works fine, even running the same way you did.

Strange..

Open your web inspector on tab 'network' on your browser, and the requests for your assets, maybe you'll see some denied access or something.
