### ISSUE TITLE
About django-mptt and django reversion

### ISSUE THREAD

**Issue by douglasmiranda** [django-admin-bootstrap/django-admin-bootstrap#45]
I will work on django-admin-bootstrap to support Django 1.7 and upgrade the bootstrap, so we can enjoy the new clean and beautiful Bootstrap 3.

I will remove the django-mptt and django-reversion templates, but the maintainers could create django packages, submit to pypi as a  django-admin-bootstrap component/extension.

However I will start  working on #43 and #39 

PS: The purpose of django-admin-bootstrap is to be a theme for django-admin, and not implement other complex features. So I will try to keep it always simple as possible.

**Comment by michaelkuty** [comment]
here is repo for reversion https://github.com/django-admin-bootstrap/django-admin-bootstrap-revision
and for mptt https://github.com/django-admin-bootstrap/django-admin-bootstrap-mptt

**Comment by douglasmiranda** [comment]
Hey @alrusdi If you still want to provide a new extension, I can set write permission for your user in this repo: https://github.com/django-admin-bootstrap/django-admin-bootstrap-mptt

Let me know what you think =]
