### ISSUE TITLE
Widget wrong visualization with django-recurrence + django-admin-bootstrap

### ISSUE THREAD

**Issue by Seether85** [django-admin-bootstrap/django-admin-bootstrap#59]
As per title, when trying to use the two together, I obtain this:

![1](https://cloud.githubusercontent.com/assets/8349902/5503635/ab4c01de-8779-11e4-97ac-46fffc81bfb8.png)
![2](https://cloud.githubusercontent.com/assets/8349902/5503636/ab5797f6-8779-11e4-9641-10afc7e9a98d.png)

Basically, the widget is rendered *under* the other parts of the form, and I'm unable to fix it without messing up with the css code... I've already posted this issue to django-recurrence developers (https://github.com/django-recurrence/django-recurrence/issues/34), and I've been told perhaps this is a better place to ask for help about it. Thank you for any help you can provide!

**Comment by Seether85** [comment]
Allright, it took a while to find some time to handle this, but it seems to be working. Just add this custom css: http://pastebin.com/29guPXC9 to have things working almost fine.

Basically, the most important correction is achieved by this line:

div.recurrence-widget {
    height: 100%;
}

Anyone should of course feel free to check/improve this solution.
Cheers.

**Comment by manuelkappler** [comment]
Sorry for necromancing, but if anyone has a similar issue, I've had very good experiences with

`div.recurrence-widget{
  height: max-content;
}
`
Tested on Firefox and Chrome.
