### ISSUE TITLE
Collapsed filter menu on side bar

### ISSUE THREAD

**Issue by alutsu** [django-admin-bootstrap/django-admin-bootstrap#73]
Can you make da side bar filter menu collapsible or add a unique id for each? Thank you, your admin is awesome

**Comment by douglasmiranda** [comment]
Yes, I'm working on it. I'm trying to offer a better sidebar to deal with too many items on filter menu.

**Comment by douglasmiranda** [comment]
I'm will not work on this in the current design, but I'm considering the solution to the new future versions.
