### ISSUE TITLE
Is bootstrap_admin 0.3.3 package compatible with python3 package index?

### ISSUE THREAD

**Issue by Gaurav-t** [django-admin-bootstrap/django-admin-bootstrap#74]
I'm trying to upgrade my existing python2 code to python3 and I want to know that, Is bootstrap_admin library package can also work with python3 or not.

**Comment by douglasmiranda** [comment]
I'm not sure, I'll have to test.

We have just just this much of python code https://github.com/douglasmiranda/django-admin-bootstrap/blob/master/bootstrap_admin/templatetags/bootstrap_admin_template_tags.py

So if not compatible yet, probably will not be hard to do it.
