### ISSUE TITLE
How do you feel about bootstrap-select2 and bootstrap-fileinput?

### ISSUE THREAD

**Issue by nanuxbe** [django-admin-bootstrap/django-admin-bootstrap#81]
I have made a custom css (based on django-bootstrap-admin) and felt there was something wrong with file-inputs and dropdowns. So I added support for https://fk.github.io/select2-bootstrap-css/master.html and https://github.com/kartik-v/bootstrap-fileinput (in their simplest form - see screenshot).

Would you be interested in a PR with those 2 libraries integrated into this project?

![image](https://cloud.githubusercontent.com/assets/1215070/7074546/a405f90a-defb-11e4-877f-05c55acedfc5.png)
![image](https://cloud.githubusercontent.com/assets/1215070/7074580/e8901574-defb-11e4-935c-a5f0ffb0a44f.png)

**Comment by douglasmiranda** [comment]
I like the idea :D
I'll release the version compatible with Django 1.8 first, then I will comeback here to discuss this issue.

Would be nice if you create a branch with this feature, so we can try it =]

**Comment by nanuxbe** [comment]
Great, I'll work on that next week then :-)

**Comment by nanuxbe** [comment]
I have started work on this feature here: https://github.com/nanuxbe/django-admin-bootstrap/tree/more_boottrap_components

**Comment by michaelkuty** [comment]
+1

**Comment by douglasmiranda** [comment]
@nanuxbe Do you think it's possible to do a separated package? If so, we could create a django-admin-bootstrap/django-admin-bootstrap-forms repo, then we stay with django-admin-bootstrap as simple as possible, and add the goodies with extensions =]

**Comment by nanuxbe** [comment]
@douglasmiranda it is possible yes, but the extra bootstrap components require to add some js & css loading inside the main ``admin/base.html`` as well as inside the inlines templates.

The reason this has to be part of the base template is in order to be able to us Django's JQuery instead of having to load a separate JQuery library.

In order for a separate package to provide those while maintaining compatibility with projects that extend the admin temple further (by overriding ``admin/base_site.html`` as stated in the docs), I think the easiest/cleanest way would be to move code from current ``admin/base.html`` to ``bootstrap_admin/base.html`` and create a new ``admin/base.html`` which would inherit from it.
It would then be a matter of defining extra ``{% block %}``'s for extra js loading inside ``bootstrap_admin/base.html``.
The same procedure would be necessary for both inline templates as well.

I think this is approach would allow separate packages for select and file input.
Further more, if you consider a "global  admin bootstrap addons ecosystem" like mentioned in the other thread, this would allow each package to exist on its own and people would be able to mix & match whatever they want from their ``admin/base_site.html``, especially is said addons are able to implement templatetags for their js needs.

**Comment by douglasmiranda** [comment]
So, @nanuxbe help-me make a good decision xD

I like the idea of having the custom inputs built-in, but I still don't know if some users could find it difficult (for some reason, maybe compatibility with other packages e.g. CMS that use custom inputs). That's why I think an add-on would be nice.

I like the separated templates idea.

I understand the "jQuery load" advantage. Maybe we could use the Django's jQuery and do a fallback when not found. But I don't want to make it difficult to maintain, so if you think I'm complicating things you should stop me, (hahaha sometimes I think too much and I forget the easy way to do =/).

I don't know if I'm worrying too much, but tell me what do you think and we can move forward.

If it's better to be built-in make a Pull Request :D

And if these changes can help, you could make a pull request too =]

**Comment by nanuxbe** [comment]
Well @douglasmiranda ...

Since we both like the separate template idea, I think we should go that way. there is also clearly some digging to do on the JQuery side. I know re-using Django's JQuery works in 1.8, I haven't done all the checks yet with 1.7, you can take a look at https://github.com/nanuxbe/django-admin-bootstrap/blob/more_boottrap_components/bootstrap_admin/static/bootstrap_admin/js/base.js#L66

I haven't actually looked at Django CMS since Django 1.5 so I can't actually tell what works or doesn't work with it.
I tried django-admin-bootstrap with FeinCMS (the "next" branch) and it only needed a few trivial css changes to work (at least what I did test).

I will do a pull request with these changes, I just have had a few unplanned things happening these past two weeks and haven't had the time to do as much open-source contributing as I would have liked but if you still can wait a few days, I will get around to do the pull request. ;-)

**Comment by douglasmiranda** [comment]
No problem! Take your time :D

I'm not contributing as much as I want too, but one step at time we'll get there. =]
