### ISSUE TITLE
ImproperlyConfigured in update 0.3.5 to 0.3.6

### ISSUE THREAD

**Issue by maoaiz** [django-admin-bootstrap/django-admin-bootstrap#84]
I use Django 1.8, and with django-admin-bootstrap 0.3.5 it works, but with 0.3.6 it doesn't work.

This is the exception:
ImproperlyConfigured: bootstrap_admin: No compatible template engine foundbootstrap_admin requires one of the following engines:
['django.template.backends.django.DjangoTemplates']

**Comment by nanuxbe** [comment]
Hello,

it would look like you are using the admin sidebar without having the request template processor loaded.

Or is it maybe an update of an existing project and you are still using the old syntax for setting up templates in settings.py?


Could you post the part of your settings.py relative to setting-up templates please?

**Comment by maoaiz** [comment]
Indeed it is the second option that you mention.
I created my project with Django 1.7 and I upgraded to 1.8, so I have the old syntax of templates settings in my settings.py.

I did the next and it works:
https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/


I will consider making a Fork for improving the documentation, thank you very much.

**Comment by maoaiz** [comment]
I made a fork with an upgrade for documentation. Pull request #85
