### ISSUE TITLE
Help text

### ISSUE THREAD

**Issue by optikfluffel** [django-admin-bootstrap/django-admin-bootstrap#87]
Is there a way to add [Bootstrap's Form Help Texts](http://getbootstrap.com/css/#forms-help-text) to the generated html from `change_form.html`?

**Comment by douglasmiranda** [comment]
Maybe you could try:

```python
from django.utils.safestring import mark_safe

name = forms.CharField(help_text=mark_safe("<span class='text-primary'>help text</span>."))
```

Not beautiful, but you know, if you need... hauehuah

2 years later, I know =x
