### ISSUE TITLE
Do not support Django1.9 !

### ISSUE THREAD

**Issue by ckcnik** [django-admin-bootstrap/django-admin-bootstrap#88]
jquery file not found

**Comment by Seha16** [comment]
Yep. New path is `admin/js/vendor/jquery/jquery.js` or `admin/js/vendor/jquery/jquery.min.js` in Django 1.9

As workaround you can specify a custom template directory in `settings.py`, similar like:
```
TEMPLATES[0]['DIRS'].append('templates')
```
or
```
TEMPLATES = [
    {
       ...
        'DIRS': [
                'templates',
        ],
        ...
    },
]
```
Then, create directories and file `templates/admin/base.html` with following content:
```
{% extends "admin/base.html" %}
{% load admin_static %}

{% block jquery %}
  <script type="text/javascript" src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
{% endblock jquery %}
```

Remember runing `python manage.py collectstatic`

**Comment by killarny** [comment]
Unfortunately, the moved JS isn't the only problem with this under 1.9 - buttons for the date/time popups are missing.

**Comment by Seha16** [comment]
I guess next links will help us to understand the problem with this under 1.9:
https://docs.djangoproject.com/en/1.9/releases/1.9/#new-styling-for-contrib-admin
https://docs.djangoproject.com/en/1.9/releases/1.9/#contrib-admin-browser-support

Now CSS of date/time button is here `static/admin/css/widgets.css`
Unfortunately, linking of widgets.css into base.html wont fix the issues with date/time icons correctly.
But as workaround, you could use the /* DATE AND TIME */ part of widget.css file.
So the file `templates/admin/base.html` would look like:
```
{% extends "admin/base.html" %}
{% load admin_static %}

{% block extrastyle %}
  <style type="text/css">
    /* DATE AND TIME */
    p.datetime {
      line-height: 20px;
      margin: 0;
      padding: 0;
      color: #666;
      font-weight: bold;
    }

    .datetime span {
      white-space: nowrap;
      font-weight: normal;
      font-size: 11px;
      color: #ccc;
    }

    .datetime input, .form-row .datetime input.vDateField, .form-row .datetime input.vTimeField {
      min-width: 0;
      margin-left: 5px;
      margin-bottom: 4px;
    }

    table p.datetime {
      font-size: 11px;
      margin-left: 0;
      padding-left: 0;
    }

    .datetimeshortcuts .clock-icon, .datetimeshortcuts .date-icon {
      position: relative;
      display: inline-block;
      vertical-align: middle;
      height: 16px;
      width: 16px;
      overflow: hidden;
    }

    .datetimeshortcuts .clock-icon {
      background: url({% static "admin/img/icon-clock.svg" %}) 0 0 no-repeat;
    }

    .datetimeshortcuts a:focus .clock-icon,
    .datetimeshortcuts a:hover .clock-icon {
      background-position: 0 -16px;
    }

    .datetimeshortcuts .date-icon {
      background: url({% static "admin/img/icon-calendar.svg" %}) 0 0 no-repeat;
      top: -1px;
    }

    .datetimeshortcuts a:focus .date-icon,
    .datetimeshortcuts a:hover .date-icon {
      background-position: 0 -16px;
    }

    .timezonewarning {
      font-size: 11px;
      color: #999;
    }
  </style>
{% endblock extrastyle %}

{% block jquery %}
  <script type="text/javascript" src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script>
  <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
{% endblock jquery %}
```

Also, you could paste the extrastyle into a separate file.

**Comment by chenjianjx** [comment]
can there be a fork for 1.9 ?

**Comment by Jayatubi** [comment]
Any ETA on this issue?

**Comment by Seha16** [comment]
well, i'll try do it this weekend.

**Comment by Seha16** [comment]
Well, I hope this merge https://github.com/django-admin-bootstrap/django-admin-bootstrap/pull/95 would help fix this issue https://github.com/django-admin-bootstrap/django-admin-bootstrap/issues/88

**Comment by raighneweng** [comment]
https://github.com/Seha16/django-admin-bootstrap 
this fork solved problem on django1.9.5, thanks

**Comment by Jzarecta** [comment]
still have the same issue with jquery.js
have it on project/static/admin/js/jquery/jquery.js but still doesnt run well.

**Comment by whuhan2013** [comment]
don't support django1.10 either

TemplateSyntaxError at /admin/

'future' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
bootstrap_admin_template_tags
cache
i18n
l10n
log
static
staticfiles

**Comment by douglasmiranda** [comment]
Thanks for waiting, sorry for the delay, but now we have a release :D

https://github.com/django-admin-bootstrap/django-admin-bootstrap/releases/tag/0.3.7
