### ISSUE TITLE
Some Responsive issue

### ISSUE THREAD

**Issue by ervaibhavsinghal** [django-admin-bootstrap/django-admin-bootstrap#94]
i have face some responsive issue after using this app, can you please tell me how to fix it.
some screen-shot share with you.
![screenshot from 2016-02-22 23 11 18](https://cloud.githubusercontent.com/assets/16643006/13226882/d22e519c-d9b9-11e5-8287-e47fdb03239b.png)
![screenshot from 2016-02-22 23 13 20](https://cloud.githubusercontent.com/assets/16643006/13226903/e35b843a-d9b9-11e5-9877-11135c54cb32.png)

**Comment by douglasmiranda** [comment]
Hello @ervaibhavsinghal 

Sorry for the delay.

I can't reproduce this.

It looks like you were loading assets from cache or something.

Since now I'm back, reopen if you have any issues =]
